/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PtdRouteImport } from './routes/_ptd'
import { Route as PtdIndexRouteImport } from './routes/_ptd/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthInviteRouteImport } from './routes/auth/invite'
import { Route as AuthApplicationRouteImport } from './routes/auth/application'
import { Route as PtdAdminRouteImport } from './routes/_ptd/admin'
import { Route as PtdAdminIndexRouteImport } from './routes/_ptd/admin/index'
import { Route as PtdAdminUsersRouteImport } from './routes/_ptd/admin/users'
import { Route as PtdAdminInvitesRouteImport } from './routes/_ptd/admin/invites'

const PtdRoute = PtdRouteImport.update({
  id: '/_ptd',
  getParentRoute: () => rootRouteImport,
} as any)
const PtdIndexRoute = PtdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtdRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthInviteRoute = AuthInviteRouteImport.update({
  id: '/auth/invite',
  path: '/auth/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthApplicationRoute = AuthApplicationRouteImport.update({
  id: '/auth/application',
  path: '/auth/application',
  getParentRoute: () => rootRouteImport,
} as any)
const PtdAdminRoute = PtdAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PtdRoute,
} as any)
const PtdAdminIndexRoute = PtdAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PtdAdminRoute,
} as any)
const PtdAdminUsersRoute = PtdAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PtdAdminRoute,
} as any)
const PtdAdminInvitesRoute = PtdAdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => PtdAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof PtdAdminRouteWithChildren
  '/auth/application': typeof AuthApplicationRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof PtdIndexRoute
  '/admin/invites': typeof PtdAdminInvitesRoute
  '/admin/users': typeof PtdAdminUsersRoute
  '/admin/': typeof PtdAdminIndexRoute
}
export interface FileRoutesByTo {
  '/auth/application': typeof AuthApplicationRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/': typeof PtdIndexRoute
  '/admin/invites': typeof PtdAdminInvitesRoute
  '/admin/users': typeof PtdAdminUsersRoute
  '/admin': typeof PtdAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_ptd': typeof PtdRouteWithChildren
  '/_ptd/admin': typeof PtdAdminRouteWithChildren
  '/auth/application': typeof AuthApplicationRoute
  '/auth/invite': typeof AuthInviteRoute
  '/auth/login': typeof AuthLoginRoute
  '/_ptd/': typeof PtdIndexRoute
  '/_ptd/admin/invites': typeof PtdAdminInvitesRoute
  '/_ptd/admin/users': typeof PtdAdminUsersRoute
  '/_ptd/admin/': typeof PtdAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/auth/application'
    | '/auth/invite'
    | '/auth/login'
    | '/'
    | '/admin/invites'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth/application'
    | '/auth/invite'
    | '/auth/login'
    | '/'
    | '/admin/invites'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_ptd'
    | '/_ptd/admin'
    | '/auth/application'
    | '/auth/invite'
    | '/auth/login'
    | '/_ptd/'
    | '/_ptd/admin/invites'
    | '/_ptd/admin/users'
    | '/_ptd/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PtdRoute: typeof PtdRouteWithChildren
  AuthApplicationRoute: typeof AuthApplicationRoute
  AuthInviteRoute: typeof AuthInviteRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ptd': {
      id: '/_ptd'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PtdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ptd/': {
      id: '/_ptd/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PtdIndexRouteImport
      parentRoute: typeof PtdRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/invite': {
      id: '/auth/invite'
      path: '/auth/invite'
      fullPath: '/auth/invite'
      preLoaderRoute: typeof AuthInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/application': {
      id: '/auth/application'
      path: '/auth/application'
      fullPath: '/auth/application'
      preLoaderRoute: typeof AuthApplicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ptd/admin': {
      id: '/_ptd/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof PtdAdminRouteImport
      parentRoute: typeof PtdRoute
    }
    '/_ptd/admin/': {
      id: '/_ptd/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof PtdAdminIndexRouteImport
      parentRoute: typeof PtdAdminRoute
    }
    '/_ptd/admin/users': {
      id: '/_ptd/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof PtdAdminUsersRouteImport
      parentRoute: typeof PtdAdminRoute
    }
    '/_ptd/admin/invites': {
      id: '/_ptd/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof PtdAdminInvitesRouteImport
      parentRoute: typeof PtdAdminRoute
    }
  }
}

interface PtdAdminRouteChildren {
  PtdAdminInvitesRoute: typeof PtdAdminInvitesRoute
  PtdAdminUsersRoute: typeof PtdAdminUsersRoute
  PtdAdminIndexRoute: typeof PtdAdminIndexRoute
}

const PtdAdminRouteChildren: PtdAdminRouteChildren = {
  PtdAdminInvitesRoute: PtdAdminInvitesRoute,
  PtdAdminUsersRoute: PtdAdminUsersRoute,
  PtdAdminIndexRoute: PtdAdminIndexRoute,
}

const PtdAdminRouteWithChildren = PtdAdminRoute._addFileChildren(
  PtdAdminRouteChildren,
)

interface PtdRouteChildren {
  PtdAdminRoute: typeof PtdAdminRouteWithChildren
  PtdIndexRoute: typeof PtdIndexRoute
}

const PtdRouteChildren: PtdRouteChildren = {
  PtdAdminRoute: PtdAdminRouteWithChildren,
  PtdIndexRoute: PtdIndexRoute,
}

const PtdRouteWithChildren = PtdRoute._addFileChildren(PtdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PtdRoute: PtdRouteWithChildren,
  AuthApplicationRoute: AuthApplicationRoute,
  AuthInviteRoute: AuthInviteRoute,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
